import type { CardTheme } from "../types";

/** Nebula 玻璃卡 · 渐变字 + 左齐色带 */
export default {
  id: "nebula",
  name: "星云玻璃",
  group: "modern",
  description: "渐变标题 + 紫蓝外框，左齐现代排版",
  format: "xhs",
  colors: {
    background: "#ffffff",
    text: "#2d2a4a",
    heading: "#7c3aed",
    accent: "#a855f7",
    codeBackground: "#f3e8ff",
    codeText: "#6b21a8",
    blockquoteBorder: "#c4b5fd",
    blockquoteBackground: "rgba(167, 139, 250, 0.12)",
    frame: "linear-gradient(145deg, #ddd6fe 0%, #bfdbfe 45%, #fbcfe8 100%)",
    headingGradient: "linear-gradient(90deg, #7c3aed, #ec4899)",
    highlight: "#fef08a",
  },
  typography: {
    fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", sans-serif',
    headingFontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", sans-serif',
    baseFontSize: 27,
    headingScale: [2.15, 1.55, 1.3, 1.15, 1.05, 1.0],
    lineHeight: 1.7,
    headingWeight: 800,
    textWeight: 400,
    textAlign: "left",
  },
  spacing: {
    padding: [48, 56, 64, 56],
    blockGap: 24,
    paragraphGap: 16,
  },
  border: {
    width: 0,
    style: "none",
    color: "transparent",
    radius: 28,
  },
  decorations: {
    chrome: "nebula",
    corners: "none",
    brandLabel: "LIZHI NEBULA",
    watermark: "DESIGNED WITH 狸知",
    watermarkPosition: "footer-center",
    headerStyle: "none",
    footerStyle: "brand",
    mascot: "none",
    heroMode: "first-h1",
    skin: "nebula",
  },
  builtin: true,
} satisfies CardTheme;
